# Generated by Django 5.2.8 on 2025-11-24 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'directors',
            },
        ),
        migrations.CreateModel(
            name='VideoProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'videoproducts',
            },
        ),
        migrations.CreateModel(
            name='DirectorsToVideoProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directorstovideo', to='sqll.directors')),
                ('video_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directorstovideo', to='sqll.videoproducts')),
            ],
            options={
                'db_table': 'directorstovideo',
            },
        ),
    ]
