# Generated by Django 5.2.7 on 2025-12-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqll', '0002_people_remove_directorstovideoproducts_director_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Starships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=128)),
                ('manufacturer', models.CharField(max_length=250)),
                ('cost_in_credits', models.IntegerField()),
                ('length', models.IntegerField()),
                ('max_atmosphering_speed', models.IntegerField()),
                ('crew', models.IntegerField()),
                ('passengers', models.IntegerField()),
                ('cargo_capacity', models.IntegerField()),
                ('consumables', models.CharField(max_length=128)),
                ('hyperdrive_rating', models.IntegerField()),
                ('MGLT', models.IntegerField()),
                ('starship_class', models.CharField(max_length=128)),
                ('pilots', models.CharField(max_length=128)),
                ('films', models.CharField(max_length=128)),
            ],
        ),
    ]
