# Generated by Django 5.2.7 on 2025-12-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqll', '0004_alter_people_height_alter_people_mass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='films',
        ),
        migrations.RemoveField(
            model_name='people',
            name='species',
        ),
        migrations.RemoveField(
            model_name='people',
            name='starships',
        ),
        migrations.RemoveField(
            model_name='people',
            name='vehicles',
        ),
        migrations.AlterField(
            model_name='people',
            name='height',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='homeworld',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='mass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
