# Generated by Django 6.0 on 2025-12-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqll', '0005_remove_people_films_remove_people_species_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='starships',
            name='films',
        ),
        migrations.RemoveField(
            model_name='starships',
            name='pilots',
        ),
        migrations.AlterField(
            model_name='starships',
            name='MGLT',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='starships',
            name='cargo_capacity',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='starships',
            name='cost_in_credits',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='starships',
            name='crew',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='starships',
            name='hyperdrive_rating',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='starships',
            name='length',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='starships',
            name='max_atmosphering_speed',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='starships',
            name='passengers',
            field=models.CharField(max_length=128),
        ),
    ]
