# Generated by Django 5.2.7 on 2025-12-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('height', models.IntegerField()),
                ('mass', models.IntegerField()),
                ('hair_color', models.CharField(max_length=100)),
                ('skin_color', models.CharField(max_length=100)),
                ('eye_color', models.CharField(max_length=100)),
                ('birth_year', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('homeworld', models.CharField(max_length=100)),
                ('films', models.CharField(max_length=200)),
                ('species', models.CharField(max_length=200)),
                ('vehicles', models.CharField(max_length=200)),
                ('starships', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='directorstovideoproducts',
            name='director',
        ),
        migrations.RemoveField(
            model_name='directorstovideoproducts',
            name='video_products',
        ),
        migrations.DeleteModel(
            name='Directors',
        ),
        migrations.DeleteModel(
            name='DirectorsToVideoProducts',
        ),
        migrations.DeleteModel(
            name='VideoProducts',
        ),
    ]
