# Generated by Django 5.2.7 on 2025-12-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqll', '0003_starships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='height',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='people',
            name='mass',
            field=models.CharField(max_length=100),
        ),
    ]
