# Generated by Django 6.0 on 2025-12-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqll', '0006_remove_starships_films_remove_starships_pilots_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='starships',
            name='pilots',
            field=models.ManyToManyField(related_name='starships', to='sqll.people'),
        ),
    ]
